name: crypto_font_icons_example
description: Crypto Font Flutter Gallery

dependencies:
  flutter:
    sdk: flutter
  crypto_font_icons:
    git:
      url: https://github.com/casabian/cryptofont-flutter.git
flutter:
  uses-material-design: true
